language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
before_install:
<<<<<<< HEAD
 - gem update --system
 - gem --version
script: 
 bundle install
 bundle exec jekyll build
=======
  - gem update --system
  - gem --version
script: 
 bundle install
 bundle exec jekyll build
>>>>>>> origin/master
