# Site settings
title: Monad's Blog
SEOTitle: Monad's Blog
header-img: http://olrr17ktb.bkt.clouddn.com/17-2-23/18674006-file_1487813631219_ab9e.jpg
email: 12g0p20xy@gmail.com
description: "Monad的前端个人博客，关注设计和代码。"
baseurl: ""
url: "12g0p20xy.github.io"
keyword: "前端, 设计"

# SNS settings
RSS: false
twitter: MonadoProxy
github:  12g0p20xy
tumblr: monadblog
dribbble: monad
douban: 75875785

highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true # if you want to customize anchor. check out line:193 of `post.html`

gems: [jekyll-paginate, jemoji]

markdown: kramdown
kramdown:
  input: GFM

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: monad
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu
ba_track_id: "851610262dde1b8d7f7dbea6402eff4e"
# Google
google_tracking_id: UA-89863402-1

# Sidebar settings
sidebar: false
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-avatar: /img/avatar-hux.jpg

# Featured Tags
featured-tags: false
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "Hux Blog",
        href: "//huangxuan.me"
    },{
        title: "Zhihu",
        href: "//zhihu.com"
    },{
        title: "极简图床",
        href: "//yotuku.cn"
    }
]
