# Site settings
title: Monad's Blog
SEOTitle: Monad's Blog
header-img: img/post-bg-cv.jpg
email: 12g0p20xy@gmail.com
description: "monad's personal blog, about designing and coding"
baseurl: ""
url: "12g0p20xy.github.io"
keyword: ""

# SNS settings
RSS: false
twitter: MonadoProxy
github:  12g0p20xy
tumblr: monadblog
dribbble: monad
douban: 75875785

highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true # if you want to customize anchor. check out line:193 of `post.html`

gems: [jekyll-paginate, jemoji]

markdown: kramdown
kramdown:
  input: GFM

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: monad
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu
ba_track_id: 
# Google
google_tracking_id: UA-89863402-1

# Sidebar settings
sidebar: false
sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-avatar: /img/avatar-hux.jpg

# Featured Tags
featured-tags: false
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]
